### ISSUE TITLE
Error running promoter-calculator

### ISSUE THREAD

**Issue by Hassan-1991** [barricklab/promoter-calculator#1]
Hi, I'm trying to run promoter-calculator on a bacterial genome sequence file, but keep running into the same error.

Here's the code I'm running:

`promoter-calculator -i REL606.fasta -o promotercalc.test -v 2 -j 72
`
The error:

```
Traceback (most recent call last):
  File "./miniconda3/bin/promoter-calculator", line 8, in <module>
    sys.exit(main())
  File "./miniconda3/lib/python3.9/site-packages/promoter_calculator/cli.py", line 107, in main
    output = promoter_calculator(sequence, verbosity = options.v, threads = options.j, circular=options.c)
  File "./miniconda3/lib/python3.9/site-packages/promoter_calculator/wrapper.py", line 196, in promoter_calculator
    result, num_hits, average = _run_calculator(sequence, 0, len(sequence), 0, callback=callback)
  File "./miniconda3/lib/python3.9/site-packages/promoter_calculator/wrapper.py", line 56, in _run_calculator
    calc = Promoter_Calculator(threads=threads, verbosity=verbosity)
  File "./miniconda3/lib/python3.9/site-packages/promoter_calculator/promoter_calculator.py", line 286, in __init__
    self.two_mer_encoder   = kmer_encoders(k = 2)
  File "./miniconda3/lib/python3.9/site-packages/promoter_calculator/util.py", line 231, in kmer_encoders
    onehot_encoder = OneHotEncoder(sparse_output=False)
TypeError: __init__() got an unexpected keyword argument 'sparse_output'
```

**Comment by croots** [comment]
What version of sklearn do you have and if it is earlier than 1.2 could you try again with a more up to date release of it?

**Comment by Hassan-1991** [comment]
Thanks - I installed the latest version of scikitlearn, and now the program is working as intended.
